name: Leap Year Push Test
on:
  [push]

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./



    env:
      MODE: "dev"

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Test Leapyear
        run: pytest test_leapyear.py

